[tools]
go = "1.24"

[env]
_.path = ["{{config_root}}/bin"]

[tasks.test]
run = "go test ./..."

[tasks.hctb]
run = "go run ./cmd/hctb"
env = { _.file = ".env" }

[tasks.build]
run = "go build -o bin/hctb ./cmd/hctb"
